# Generated by Django 5.1.2 on 2024-10-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(default='boate', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('informacao', models.TextField(blank=True, null=True)),
                ('imagem', models.CharField(blank=True, default='imagens/rick_roll.jpg', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('peso', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('armazenado', 'Armazenado'), ('reciclado', 'Reciclado'), ('descartado', 'Descartado')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
