# Generated by Django 5.1.3 on 2024-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_ong_endereco_alter_ong_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ong',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
