# Generated by Django 5.1.3 on 2024-11-26 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_avaliacaoong_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoong',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoong',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
