# Generated by Django 5.1.3 on 2024-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_ong_capacidade_maxima_ong_telefone_ong_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='horario_funcionamento',
            field=models.CharField(default='das 8 ás 17h', max_length=255),
        ),
    ]
