# Generated by Django 5.1.3 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_ong_horario_funcionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='whatsapp',
            field=models.CharField(default='5581994382896', max_length=30),
        ),
    ]
